production:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: true
  database: oav_production
  pool: 5
  host: <%= ENV['APP_DB_HOST'] %>
  port: <%= ENV['APP_DB_PORT'] || "3306" %>
  database: <%= ENV['APP_DB_DATABASE'] %>
  username: <%= ENV['APP_DB_USERNAME'] %>
  password: <%= ENV['APP_DB_PASSWORD'] %>
  rsk_soap_username: <%= ENV['SOAP_USERNAME'] %>
  rsk_soap_password: <%= ENV['SOAP_PASSWORD'] %>
  rsk_url: https://www.island.is/audkenning?id=ktest.betrireykjavik.is
  rr_url: https://rafraen.reykjavik.is/pages/betrireykjavikaudkenning?return_url=ktest.betrireykjavik.is

development: 
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: true
  database: oav_development
  pool: 5
  username: root
  password: bjahdh69
  rsk_soap_username: 
  rsk_soap_password:
  rsk_url: https://www.island.is/audkenning?id=ktest.betrireykjavik.is
  rr_url: https://rafraen.reykjavik.is/pages/betrireykjavikaudkenning?return_url=ktest.betrireykjavik.is

test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  reconnect: true
  database: oav_test
  pool: 5
  username: root 
  password: bjahdh69
  rsk_soap_username:
  rsk_soap_password:
  rsk_url: https://www.island.is/audkenning?id=ktest.betrireykjavik.is
  rr_url: https://rafraen.reykjavik.is/pages/betrireykjavikaudkenning?return_url=ktest.betrireykjavik.is
